### ISSUE TITLE
Source-url unreachable

### ISSUE THREAD

**Issue by thundergnat** [jmaslak/Raku-App-Task#1]
The source-url in the META6.json file does not seem to be reachable. Will make zef installation more difficult and misdirects from Raku.land. Unless there is a compelling reason otherwise, probably would be better to point to this repository.

Cheers!

**Comment by jmaslak** [comment]
Fixed (I think) with https://github.com/jmaslak/Raku-App-Task/commit/c42ce6bfc1a2342bdbf8aaaa435bb51201de4c33.  I'm working on some other code in the repo but expect to be ready to push a new release over the next day or so.

**Comment by jmaslak** [comment]
New release created as 0.3.0.
